---
- name: Set python env
  set_fact:
    ansible_python_interpreter: "{{ansible_env.HOME}}/.pyenv/shims/python"

- name: create basic auth users
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{item.basic_auth_username}}"
    password: "{{item.basic_auth_password}}"
    owner: www-data
    group: www-data
    mode: 0644
  loop: "{{basic_auth_users}}"
  become: yes
  notify:
   - restart nginx
...
