---
version: "2"
services:
  app:
    image: sonarqube:7.9.6-community
    container_name: sonarqube
    depends_on:
      - db
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
      nproc:
        soft: "4096"
        hard: "4096"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
  db:
    image: postgres:9.6.15-alpine
    container_name:  postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  web:
    image: "nginx:1.17.5"
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx-conf:/etc/nginx/conf.d/"
      - "./ssl:/etc/nginx/ssl"
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
...
