---  
- name: Create directory if it does not exist
  file:
    path: '{{ansible_env.HOME}}/.m2/repository'
    state: directory
    mode: "0755"

- name: copy maven config
  template:
    src: settings.xml
    dest: '{{ansible_env.HOME}}/.m2/'
...
