---
version: "2"
services:

  prometheus:
    image: prom/prometheus:v2.30.0
    container_name: prometheus
    volumes:
      - "./prometheus:/etc/prometheus"
      - "prometheus_db:/prometheus"
    ports:
    - "9090:9090"        
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://prometheus.tourmachine.net/'
      - '--web.enable-lifecycle'
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    volumes:
      - "alertmanager_data:/alertmanager"
      - "./alertmanager:/etc/alertmanager"
    ports:
    - "9093:9093"  
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://alertmanager.tourmachine.net/'

  grafana:
    image: grafana/grafana:8.1.5-ubuntu
    container_name: grafana
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
    ports:
    - "3000:3000"  
    restart: always
    user: "472"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD={{grafana_password}}
      - GF_SERVER_ROOT_URL=https://grafana.tourmachine.net/

volumes:
  prometheus_db:
  alertmanager_data:
...
