---

- name: Create a bashrc.d directory if it does not exist
  file:
    path: "{{item.0.user_home | default('/home/' + item.0.user_name)}}/.bashrc.d"
    state: directory
    owner: "{{item.0.user_name}}"
    group: "{{item.0.user_name}}"
    mode: '0755'  
  become: true

- name: enable separated bashrc files
  lineinfile:    
    path: "{{item.0.user_home | default('/home/' + item.0.user_name)}}/.bashrc"
    line: 'for file in ~/.bashrc.d/*.bashrc; do source $file; done'
    create: yes
  become: true

- name: Copy custom bashrc files
  copy:
    src: "{{item_fileglob}}"
    dest: "{{item.0.user_home | default('/home/' + item.0.user_name)}}/.bashrc.d/"
    owner: "{{item.0.user_name}}"
    group: "{{item.0.user_name}}"
    mode: '0644'
  with_fileglob:
    - "*.bashrc"
  loop_control:
      loop_var: item_fileglob        
  become: true
  
...  