---
version: "2"
services:
  app:
    image: sonatype/nexus3:3.27.0
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    environment:
      - JAVA_OPTS=-Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Moscow
    volumes:
      - "nexus_data:/nexus-data"

  web:
    image: "nginx:1.17.5"
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx-conf:/etc/nginx/conf.d/"
      - "./ssl:/etc/nginx/ssl"
volumes:
  nexus_data:
...
