---

- name: Install unattended upgrades packages
  yum:
    name: "{{unattended_upgrades_packages}}"
    state: present
  become: true

- name: configure unattended upgrades
  template:
      src: '{{ansible_distribution | lower }}{{ansible_distribution_major_version}}/{{item}}'
      dest: /etc/yum/
      owner: root
      group: root
      mode: 0644
  loop:
    - yum-cron-hourly.conf.j2
    - yum-cron.conf.j2
  become: true

- name: start yum-cron
  systemd:
    name: yum-cron
    enabled: yes
    state: started
  become: true

- name: configure smtp
  include_role:
    name: configure_ssmtp

...
