---

- name: Install unattended upgrades packages
  apt:
    name: "{{unattended_upgrades_packages}}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: configure unattended upgrades
  template:
      src: '{{ansible_os_family | lower}}/{{item}}'
      dest: '/etc/apt/apt.conf.d/{{ (item | splitext)[0]}}'
      owner: root
      group: root
      mode: 0644
  loop:
    - 10periodic.j2
    - 50unattended-upgrades.j2
    - 51unattended-upgrades-custom.j2
  become: true

- name: configure apticron
  lineinfile:
    path: /etc/apticron/apticron.conf
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  loop:
    - { regexp: '^EMAIL=' , line: EMAIL="george.kirillov@soft-machine.ru" }
    - { regexp: '^NOTIFY_NEW=' , line: NOTIFY_NEW="0"  }
  become: true

- name: configure smtp
  include_role:
    name: configure_ssmtp

...
