---
- name: my test
  hosts: localhost
  tasks:
  - name: runmymodule
    my_own_namespace.my_own_collection.my_own_module:
      name: "hellomotto.txt"
      path: /tmp/test
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'