---
- name: restart nginx_exporter
  become: true
  systemd:
    name: nginx_exporter
    state: "{{(nginx_exporter_service_state != 'stopped') | ternary('restarted', 'stopped')}}"
  when: nginx_exporter_service_notify and (
    _nginx_exporter_service_state is not defined or
    not ( _nginx_exporter_service_state is changed ))
