---
- name: Ensure ansible facts folder exists
  file:
    name: /etc/ansible/facts.d/
    state: directory
    recurse: yes

- name: Ensure bamboo facts exists
  file:
    name: /etc/ansible/facts.d/bamboo.fact
    state: touch
  changed_when: False

- name: Update bamboo facts
  template:
    src: bamboo.fact.j2
    dest: /etc/ansible/facts.d/bamboo.fact
  notify: restart bamboo
