---
- name: Check if Nginx is installed
  command: /usr/sbin/nginx -v
  ignore_errors: true
  changed_when: false
  register: nginxinstalled

- name: Check if Docker is installed
  command: /usr/bin/docker -v
  ignore_errors: true
  changed_when: false
  register: dockerinstalled

- name: Check if postgresql is installed
  command: /usr/lib/postgresql/12/bin/postgres -V
  ignore_errors: true
  changed_when: false
  register: postgresinstalled
...
