---
- name: Check if Nginx is installed
  command: /usr/sbin/nginx -v
  ignore_errors: true
  changed_when: false
  register: nginxinstalled

- name: Check if java is installed
  command: /bin/java -version
  ignore_errors: true
  changed_when: false
  register: javainstalled

- name: Check if tomcat
  stat:
    path: "{{tomcat_install_dir}}"
  register: file_details
...
