---
- name: group
  become: true
  group:
    name: "{{nginx_exporter_group}}"
    state: present
    system: true
  when: nginx_exporter_group_manage | bool

- name: user
  become: true
  user:
    name: "{{nginx_exporter_user}}"
    group: "{{nginx_exporter_group}}"
    home: "{{nginx_exporter_home}}"
    createhome: false
    move_home: false
    comment: nginx_exporter
    state: present
    system: true
  when: nginx_exporter_user_manage | bool

- name: home
  become: true
  file:
    path: "{{nginx_exporter_home}}"
    owner: "{{nginx_exporter_user}}"
    group: "{{nginx_exporter_group}}"
    mode: "u=rwx,g=rx,o="
    state: directory
  when: nginx_exporter_home_manage | bool

- name: logs
  become: true
  file:
    path: "{{nginx_exporter_log_path}}"
    owner: "{{nginx_exporter_user}}"
    group: "{{nginx_exporter_group}}"
    mode: "u=rwx,g=rx,o="
    state: directory

- name: download tarball
  become: true
  get_url:
    url: "{{nginx_exporter_tarball_url}}"    
    dest: "{{prometheus_exporter_dist_dir }}/{{ nginx_exporter_signature}}.tar.gz"
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: make distribution directory
  become: true
  file:
    path: "{{nginx_exporter_dist_dir}}"
    owner: root
    group: root
    mode: "u=rwx,go=rx"
    state: directory

- name: untar tarball
  become: true
  unarchive:
    src: "{{prometheus_exporter_dist_dir }}/{{ nginx_exporter_signature}}.tar.gz"
    dest: "{{nginx_exporter_dist_dir}}"
    remote_src: true
    owner: root
    group: root
    mode: "u=rwx,go=rx"
    creates: "{{nginx_exporter_dist_dir}}/nginx-prometheus-exporter"

- name: symlink
  become: true
  file:
    src: "{{nginx_exporter_dist_dir}}/nginx-prometheus-exporter"
    path: "{{prometheus_exporter_dir}}/nginx_exporter"
    owner: root
    group: root
    force: true
    state: link
  notify: restart nginx_exporter

- name: config
  become: true
  template:
    src: "nginx_exporter.default.conf.j2"
    dest: "/etc/default/nginx_exporter"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify: restart nginx_exporter

- name: systemd service
  become: true
  template:
    src: "nginx_exporter.systemd.j2"
    dest: "/lib/systemd/system/nginx_exporter.service"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - restart nginx_exporter

- name: Service Enabled
  become: true
  systemd:
    name: nginx_exporter
    enabled: "{{nginx_exporter_service_enable}}"
    state: "{{nginx_exporter_service_state}}"

