---
- name: Includeing OS specific variables
  include_vars: "{{ansible_os_family | lower}}.yml"

- import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
...
