---

- name: set_fact - get groups as list per server
  set_fact:
    groups_as_list: "{{(groups_as_list|default([]) + item.0.user_groups.split(','))|map('trim')|list|sort|unique}}"  
  loop: "{{users_params|subelements('servers')}}"
  loop_control:
    label: "user_name: {{item.0.user_name }}, groups_as_list: {{ item.0.user_groups if item.0.user_groups is defined else ''}}"
  when: item.0.user_groups is defined and item.1 in group_names

- name: creat group
  group:
    name: "{{item}}"
    state: present
  loop: "{{groups_as_list}}"
  become: yes

...
