---
- name: Version selection
  include_vars: "{{openjdk_version | default('openjdk13', true)}}.yml"

- block:
  - name: Create a directory if it does not exist
    file:
      path: "{{openjdk_install_directory}}"
      state: directory
      mode: '0755'

  - name: Download JDK tarball
    unarchive:
      src: "{{openjdk_url}}"
      dest: "{{openjdk_install_directory}}"
      list_files: yes
      remote_src: yes
    register: archive_contents

  - name: update alternatives for java
    alternatives:
      name: java
      path: '{{openjdk_install_directory }}/{{ archive_contents.files[0].split("/")[0]}}/bin/java'
      link: /usr/bin/java
      priority: 20000

  - name: set java home as environment variable
    blockinfile:
      insertafter: EOF
      path: /etc/environment
      block: 'export JAVA_HOME={{openjdk_install_directory }}/{{ archive_contents.files[0].split("/")[0]}}'

  become: True
  when: openjdk_url is defined
...
