---
- hosts:
  - nfs.soft-machine.tech
  - nfs
  tasks:

    - name: install nfs
      import_role:
        name: install_nfs_server
      vars:
        nfs_dir: "/srv/share"
        nfs_network_access: "*"
...
