---
- hosts: mssql.soft-machine.tech
  tasks:

    - name: install pyenv
      import_role:
        name: manage_python_packages
      vars:
        pyenv_virtualenv: ansible_python3
        python_packages:
          - docker
          - PyYAML
          - docker-compose
      tags: pyenv

    - name: install docker engine
      import_role:
        name: install_docker
      tags: docker

    - name: login in private registry
      import_role:
        name: docker_login
      tags: docker_login

    - name: deploy cadvisor
      import_role:
        name: deploy_docker
      vars:
        docker_container_params:
          - docker_container_name: "cadvisor"
            docker_container_image: "google/cadvisor:v0.33.0"
            docker_container_volumes:
              - /:/rootfs:ro
              - /var/run:/var/run:rw
              - /sys:/sys:ro
              - /var/lib/docker/:/var/lib/docker:ro
            docker_container_ports:
              - "8888:8080"
            docker_container_restart_policy: always
      tags: cadvisor

    - name: deploy compose
      import_role:
        name: deploy_compose
      tags: deploy_compose

...
