---
- name: Create a directory if it does not exist
  file:
    path: "{{nginx_ssl_dir}}"
    state: directory
    mode: "0755"
  become: true

- name: Copy ssl certificate
  copy:
    src: "{{item}}"
    dest: "{{nginx_ssl_dir}}"
    mode: '0644'
  with_fileglob:
    - "ssl/*"
  become: true
  notify: restart nginx

- name: Copy nginx config
  copy:
    src: 'nginx_conf/{{inventory_hostname}}/'
    dest: /etc/nginx/conf.d/
    mode: '0644'
  become: true
  notify: restart nginx

- name: Check NGINX configs
  shell: "/usr/sbin/nginx -t"
  changed_when: false
  become: true
...
