---

- name: including OS specific variables
  include_vars: "{{ansible_os_family | lower}}.yml"

- name: Disallow password authentication & root ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  loop:
    - { regexp: '^#*PasswordAuthentication\s', line: 'PasswordAuthentication no' }
    - { regexp: '^#*PermitRootLogin\s', line: 'PermitRootLogin no' }
  become: true
  notify: Restart ssh

...
